package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.AdminManage;

import java.util.List;

public interface AdminManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_manage
     *
     * @mbggenerated
     */
    int insert(AdminManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_manage
     *
     * @mbggenerated
     */
    AdminManage selectByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_manage
     *
     * @mbggenerated
     */
    List<AdminManage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminManage record);



    int countAdminManage();


}