package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.DateStatistics;

import java.util.Date;
import java.util.List;

public interface DateStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_statistics
     *
     * @mbggenerated
     */
    int insert(DateStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_statistics
     *
     * @mbggenerated
     */
    DateStatistics selectByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_statistics
     *
     * @mbggenerated
     */
    List<DateStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DateStatistics record);
}