package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.Helper;

import java.util.List;

public interface HelperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int insert(Helper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    Helper selectByPrimaryKey(String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    List<Helper> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Helper record);
}