package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.MonthStatistics;

import java.util.Date;
import java.util.List;

public interface MonthStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Date year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_statistics
     *
     * @mbggenerated
     */
    int insert(MonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_statistics
     *
     * @mbggenerated
     */
    MonthStatistics selectByPrimaryKey(Date year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_statistics
     *
     * @mbggenerated
     */
    List<MonthStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonthStatistics record);
}