package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.OrderManage;

import java.util.List;

public interface OrderManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_manage
     *
     * @mbggenerated
     */
    int insert(OrderManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_manage
     *
     * @mbggenerated
     */
    OrderManage selectByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_manage
     *
     * @mbggenerated
     */
    List<OrderManage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderManage record);

    int countOrderManage();
}