package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.RefundRecord;

import java.util.List;

public interface RefundRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_record
     *
     * @mbggenerated
     */
    int insert(RefundRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_record
     *
     * @mbggenerated
     */
    RefundRecord selectByPrimaryKey(Long usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_record
     *
     * @mbggenerated
     */
    List<RefundRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RefundRecord record);
}