package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.SeasonStatistics;

import java.util.Date;
import java.util.List;

public interface SeasonStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Date year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_statistics
     *
     * @mbggenerated
     */
    int insert(SeasonStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_statistics
     *
     * @mbggenerated
     */
    SeasonStatistics selectByPrimaryKey(Date year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_statistics
     *
     * @mbggenerated
     */
    List<SeasonStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SeasonStatistics record);
}