package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.AdminPerms;
import java.util.List;

public interface AdminPermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms
     *
     * @mbggenerated
     */
    int insert(AdminPerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms
     *
     * @mbggenerated
     */
    AdminPerms selectByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms
     *
     * @mbggenerated
     */
    List<AdminPerms> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_perms
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminPerms record);
}