package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.Coupon;

import java.util.List;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    Coupon selectByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    List<Coupon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Coupon record);
}