package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.PayRecord;

import java.util.List;

public interface PayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbggenerated
     */
    int insert(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbggenerated
     */
    PayRecord selectByPrimaryKey(Long usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbggenerated
     */
    List<PayRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayRecord record);
}