package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.PushCouponRecord;

import java.util.List;

public interface PushCouponRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_coupon_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_coupon_record
     *
     * @mbggenerated
     */
    int insert(PushCouponRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_coupon_record
     *
     * @mbggenerated
     */
    PushCouponRecord selectByPrimaryKey(Long couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_coupon_record
     *
     * @mbggenerated
     */
    List<PushCouponRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_coupon_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PushCouponRecord record);
}