package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.UsrAdvice;

import java.util.List;

public interface UsrAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_advice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_advice
     *
     * @mbggenerated
     */
    int insert(UsrAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_advice
     *
     * @mbggenerated
     */
    UsrAdvice selectByPrimaryKey(Long usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_advice
     *
     * @mbggenerated
     */
    List<UsrAdvice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsrAdvice record);
}