package com.monster.greenfruit.dao;

import com.monster.greenfruit.pojo.domain.UsrManage;

import java.util.List;

public interface UsrManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage
     *
     * @mbggenerated
     */
    int insert(UsrManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage
     *
     * @mbggenerated
     */
    UsrManage selectByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage
     *
     * @mbggenerated
     */
    List<UsrManage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsrManage record);

    int countUsrManage();
}