package com.monster.greenfruit.pojo.domain;

public class AdminPerms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_perms.admin_id
     *
     * @mbggenerated
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_perms.permission
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_perms.admin_role
     *
     * @mbggenerated
     */
    private String adminRole;

    public AdminPerms(){ }

    public AdminPerms(Long adminId, String permission, String adminRole) {
        this.adminId = adminId;
        this.permission = permission;
        this.adminRole = adminRole;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_perms.admin_id
     *
     * @return the value of admin_perms.admin_id
     *
     * @mbggenerated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_perms.admin_id
     *
     * @param adminId the value for admin_perms.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_perms.permission
     *
     * @return the value of admin_perms.permission
     *
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_perms.permission
     *
     * @param permission the value for admin_perms.permission
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_perms.admin_role
     *
     * @return the value of admin_perms.admin_role
     *
     * @mbggenerated
     */
    public String getAdminRole() {
        return adminRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_perms.admin_role
     *
     * @param adminRole the value for admin_perms.admin_role
     *
     * @mbggenerated
     */
    public void setAdminRole(String adminRole) {
        this.adminRole = adminRole == null ? null : adminRole.trim();
    }
}