package com.monster.greenfruit.pojo.domain;

import com.monster.greenfruit.pojo.dto.AdminDTO;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbggenerated
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_cellphone
     *
     * @mbggenerated
     */
    private String adminCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_identity
     *
     * @mbggenerated
     */
    private String adminIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_salt
     *
     * @mbggenerated
     */
    private String adminSalt;


    private String district;

    public Admin() { }

    public Admin(AdminDTO adminDTO) {
        this.sex = adminDTO.getSex();
        this.adminSalt = adminDTO.getAdminSalt();
        this.adminIdentity = adminDTO.getAdminIdentity();
        this.password = adminDTO.getPassword();
        this.level = adminDTO.getLevel();
        this.adminCellphone = adminDTO.getAdminCellphone();
        this.adminName = adminDTO.getAdminName();
        this.district=adminDTO.getDistrict();
    }


    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     * @mbggenerated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     * @mbggenerated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     * @mbggenerated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     * @mbggenerated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_cellphone
     *
     * @return the value of admin.admin_cellphone
     * @mbggenerated
     */
    public String getAdminCellphone() {
        return adminCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_cellphone
     *
     * @param adminCellphone the value for admin.admin_cellphone
     * @mbggenerated
     */
    public void setAdminCellphone(String adminCellphone) {
        this.adminCellphone = adminCellphone == null ? null : adminCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_identity
     *
     * @return the value of admin.admin_identity
     * @mbggenerated
     */
    public String getAdminIdentity() {
        return adminIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_identity
     *
     * @param adminIdentity the value for admin.admin_identity
     * @mbggenerated
     */
    public void setAdminIdentity(String adminIdentity) {
        this.adminIdentity = adminIdentity == null ? null : adminIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.level
     *
     * @return the value of admin.level
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.level
     *
     * @param level the value for admin.level
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_salt
     *
     * @return the value of admin.admin_salt
     * @mbggenerated
     */
    public String getAdminSalt() {
        return adminSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_salt
     *
     * @param adminSalt the value for admin.admin_salt
     * @mbggenerated
     */
    public void setAdminSalt(String adminSalt) {
        this.adminSalt = adminSalt == null ? null : adminSalt.trim();
    }
}