package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_id
     *
     * @mbggenerated
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.usr_cellphone
     *
     * @mbggenerated
     */
    private String usrCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_status
     *
     * @mbggenerated
     */
    private Integer couponStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_type
     *
     * @mbggenerated
     */
    private Integer couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.stationary_value
     *
     * @mbggenerated
     */
    private Integer stationaryValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.discount_value
     *
     * @mbggenerated
     */
    private Float discountValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.threshold_value
     *
     * @mbggenerated
     */
    private Integer thresholdValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.applicable_area
     *
     * @mbggenerated
     */
    private String applicableArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_id
     *
     * @return the value of coupon.coupon_id
     * @mbggenerated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_id
     *
     * @param couponId the value for coupon.coupon_id
     * @mbggenerated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.usr_cellphone
     *
     * @return the value of coupon.usr_cellphone
     * @mbggenerated
     */
    public String getUsrCellphone() {
        return usrCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.usr_cellphone
     *
     * @param usrCellphone the value for coupon.usr_cellphone
     * @mbggenerated
     */
    public void setUsrCellphone(String usrCellphone) {
        this.usrCellphone = usrCellphone == null ? null : usrCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_status
     *
     * @return the value of coupon.coupon_status
     * @mbggenerated
     */
    public Integer getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_status
     *
     * @param couponStatus the value for coupon.coupon_status
     * @mbggenerated
     */
    public void setCouponStatus(Integer couponStatus) {
        this.couponStatus = couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_type
     *
     * @return the value of coupon.coupon_type
     * @mbggenerated
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_type
     *
     * @param couponType the value for coupon.coupon_type
     * @mbggenerated
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.stationary_value
     *
     * @return the value of coupon.stationary_value
     * @mbggenerated
     */
    public Integer getStationaryValue() {
        return stationaryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.stationary_value
     *
     * @param stationaryValue the value for coupon.stationary_value
     * @mbggenerated
     */
    public void setStationaryValue(Integer stationaryValue) {
        this.stationaryValue = stationaryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.discount_value
     *
     * @return the value of coupon.discount_value
     * @mbggenerated
     */
    public Float getDiscountValue() {
        return discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.discount_value
     *
     * @param discountValue the value for coupon.discount_value
     * @mbggenerated
     */
    public void setDiscountValue(Float discountValue) {
        this.discountValue = discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.start_time
     *
     * @return the value of coupon.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.start_time
     *
     * @param startTime the value for coupon.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.end_time
     *
     * @return the value of coupon.end_time
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.end_time
     *
     * @param endTime the value for coupon.end_time
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.describe
     *
     * @return the value of coupon.describe
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.describe
     *
     * @param describe the value for coupon.describe
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.threshold_value
     *
     * @return the value of coupon.threshold_value
     * @mbggenerated
     */
    public Integer getThresholdValue() {
        return thresholdValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.threshold_value
     *
     * @param thresholdValue the value for coupon.threshold_value
     * @mbggenerated
     */
    public void setThresholdValue(Integer thresholdValue) {
        this.thresholdValue = thresholdValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.applicable_area
     *
     * @return the value of coupon.applicable_area
     * @mbggenerated
     */
    public String getApplicableArea() {
        return applicableArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.applicable_area
     *
     * @param applicableArea the value for coupon.applicable_area
     * @mbggenerated
     */
    public void setApplicableArea(String applicableArea) {
        this.applicableArea = applicableArea == null ? null : applicableArea.trim();
    }
}