package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class PayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.usr_id
     *
     * @mbggenerated
     */
    private Long usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.pay_money
     *
     * @mbggenerated
     */
    private Long payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.trade_id
     *
     * @mbggenerated
     */
    private String tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.pay_date
     *
     * @mbggenerated
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.usr_id
     *
     * @return the value of pay_record.usr_id
     * @mbggenerated
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.usr_id
     *
     * @param usrId the value for pay_record.usr_id
     * @mbggenerated
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.pay_money
     *
     * @return the value of pay_record.pay_money
     * @mbggenerated
     */
    public Long getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.pay_money
     *
     * @param payMoney the value for pay_record.pay_money
     * @mbggenerated
     */
    public void setPayMoney(Long payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.order_id
     *
     * @return the value of pay_record.order_id
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.order_id
     *
     * @param orderId the value for pay_record.order_id
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.trade_id
     *
     * @return the value of pay_record.trade_id
     * @mbggenerated
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.trade_id
     *
     * @param tradeId the value for pay_record.trade_id
     * @mbggenerated
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.pay_date
     *
     * @return the value of pay_record.pay_date
     * @mbggenerated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.pay_date
     *
     * @param payDate the value for pay_record.pay_date
     * @mbggenerated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.pay_status
     *
     * @return the value of pay_record.pay_status
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.pay_status
     *
     * @param payStatus the value for pay_record.pay_status
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.pay_type
     *
     * @return the value of pay_record.pay_type
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.pay_type
     *
     * @param payType the value for pay_record.pay_type
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }
}