package com.monster.greenfruit.pojo.domain;

public class Usr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.usr_id
     *
     * @mbggenerated
     */
    private Long usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.usr_cellphone
     *
     * @mbggenerated
     */
    private String usrCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.usr_address
     *
     * @mbggenerated
     */
    private String usrAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.longitude
     *
     * @mbggenerated
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.latitude
     *
     * @mbggenerated
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.usr_salt
     *
     * @mbggenerated
     */
    private String usrSalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.usr_id
     *
     * @return the value of usr.usr_id
     *
     * @mbggenerated
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.usr_id
     *
     * @param usrId the value for usr.usr_id
     *
     * @mbggenerated
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.password
     *
     * @return the value of usr.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.password
     *
     * @param password the value for usr.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.usr_cellphone
     *
     * @return the value of usr.usr_cellphone
     *
     * @mbggenerated
     */
    public String getUsrCellphone() {
        return usrCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.usr_cellphone
     *
     * @param usrCellphone the value for usr.usr_cellphone
     *
     * @mbggenerated
     */
    public void setUsrCellphone(String usrCellphone) {
        this.usrCellphone = usrCellphone == null ? null : usrCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.usr_address
     *
     * @return the value of usr.usr_address
     *
     * @mbggenerated
     */
    public String getUsrAddress() {
        return usrAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.usr_address
     *
     * @param usrAddress the value for usr.usr_address
     *
     * @mbggenerated
     */
    public void setUsrAddress(String usrAddress) {
        this.usrAddress = usrAddress == null ? null : usrAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.longitude
     *
     * @return the value of usr.longitude
     *
     * @mbggenerated
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.longitude
     *
     * @param longitude the value for usr.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.latitude
     *
     * @return the value of usr.latitude
     *
     * @mbggenerated
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.latitude
     *
     * @param latitude the value for usr.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.usr_salt
     *
     * @return the value of usr.usr_salt
     *
     * @mbggenerated
     */
    public String getUsrSalt() {
        return usrSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.usr_salt
     *
     * @param usrSalt the value for usr.usr_salt
     *
     * @mbggenerated
     */
    public void setUsrSalt(String usrSalt) {
        this.usrSalt = usrSalt == null ? null : usrSalt.trim();
    }
}