package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class DateStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_statistics.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_statistics.date_income
     *
     * @mbggenerated
     */
    private Long dateIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_statistics.growth_rate
     *
     * @mbggenerated
     */
    private Double growthRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_statistics.date
     *
     * @return the value of date_statistics.date
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_statistics.date
     *
     * @param date the value for date_statistics.date
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_statistics.date_income
     *
     * @return the value of date_statistics.date_income
     * @mbggenerated
     */
    public Long getDateIncome() {
        return dateIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_statistics.date_income
     *
     * @param dateIncome the value for date_statistics.date_income
     * @mbggenerated
     */
    public void setDateIncome(Long dateIncome) {
        this.dateIncome = dateIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_statistics.growth_rate
     *
     * @return the value of date_statistics.growth_rate
     * @mbggenerated
     */
    public Double getGrowthRate() {
        return growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_statistics.growth_rate
     *
     * @param growthRate the value for date_statistics.growth_rate
     * @mbggenerated
     */
    public void setGrowthRate(Double growthRate) {
        this.growthRate = growthRate;
    }
}