package com.monster.greenfruit.pojo.domain;

public class Helper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper.explain
     *
     * @mbggenerated
     */
    private String explain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column helper.type
     *
     * @return the value of helper.type
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column helper.type
     *
     * @param type the value for helper.type
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column helper.explain
     *
     * @return the value of helper.explain
     * @mbggenerated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column helper.explain
     *
     * @param explain the value for helper.explain
     * @mbggenerated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }
}