package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class Inspector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_id
     *
     * @mbggenerated
     */
    private Long inspectorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_name
     *
     * @mbggenerated
     */
    private String inspectorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_cellphone
     *
     * @mbggenerated
     */
    private String inspectorCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_identity
     *
     * @mbggenerated
     */
    private String inspectorIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.registration_date
     *
     * @mbggenerated
     */
    private Date registrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.usr_appraise
     *
     * @mbggenerated
     */
    private Integer usrAppraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.order_counts
     *
     * @mbggenerated
     */
    private Integer orderCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_salt
     *
     * @mbggenerated
     */
    private String inspectorSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.portrait_path
     *
     * @mbggenerated
     */
    private String portraitPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_id
     *
     * @return the value of inspector.inspector_id
     * @mbggenerated
     */
    public Long getInspectorId() {
        return inspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_id
     *
     * @param inspectorId the value for inspector.inspector_id
     * @mbggenerated
     */
    public void setInspectorId(Long inspectorId) {
        this.inspectorId = inspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.password
     *
     * @return the value of inspector.password
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.password
     *
     * @param password the value for inspector.password
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_name
     *
     * @return the value of inspector.inspector_name
     * @mbggenerated
     */
    public String getInspectorName() {
        return inspectorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_name
     *
     * @param inspectorName the value for inspector.inspector_name
     * @mbggenerated
     */
    public void setInspectorName(String inspectorName) {
        this.inspectorName = inspectorName == null ? null : inspectorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.sex
     *
     * @return the value of inspector.sex
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.sex
     *
     * @param sex the value for inspector.sex
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_cellphone
     *
     * @return the value of inspector.inspector_cellphone
     * @mbggenerated
     */
    public String getInspectorCellphone() {
        return inspectorCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_cellphone
     *
     * @param inspectorCellphone the value for inspector.inspector_cellphone
     * @mbggenerated
     */
    public void setInspectorCellphone(String inspectorCellphone) {
        this.inspectorCellphone = inspectorCellphone == null ? null : inspectorCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_identity
     *
     * @return the value of inspector.inspector_identity
     * @mbggenerated
     */
    public String getInspectorIdentity() {
        return inspectorIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_identity
     *
     * @param inspectorIdentity the value for inspector.inspector_identity
     * @mbggenerated
     */
    public void setInspectorIdentity(String inspectorIdentity) {
        this.inspectorIdentity = inspectorIdentity == null ? null : inspectorIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.registration_date
     *
     * @return the value of inspector.registration_date
     * @mbggenerated
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.registration_date
     *
     * @param registrationDate the value for inspector.registration_date
     * @mbggenerated
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.usr_appraise
     *
     * @return the value of inspector.usr_appraise
     * @mbggenerated
     */
    public Integer getUsrAppraise() {
        return usrAppraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.usr_appraise
     *
     * @param usrAppraise the value for inspector.usr_appraise
     * @mbggenerated
     */
    public void setUsrAppraise(Integer usrAppraise) {
        this.usrAppraise = usrAppraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.order_counts
     *
     * @return the value of inspector.order_counts
     * @mbggenerated
     */
    public Integer getOrderCounts() {
        return orderCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.order_counts
     *
     * @param orderCounts the value for inspector.order_counts
     * @mbggenerated
     */
    public void setOrderCounts(Integer orderCounts) {
        this.orderCounts = orderCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_salt
     *
     * @return the value of inspector.inspector_salt
     * @mbggenerated
     */
    public String getInspectorSalt() {
        return inspectorSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_salt
     *
     * @param inspectorSalt the value for inspector.inspector_salt
     * @mbggenerated
     */
    public void setInspectorSalt(String inspectorSalt) {
        this.inspectorSalt = inspectorSalt == null ? null : inspectorSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.portrait_path
     *
     * @return the value of inspector.portrait_path
     * @mbggenerated
     */
    public String getPortraitPath() {
        return portraitPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.portrait_path
     *
     * @param portraitPath the value for inspector.portrait_path
     * @mbggenerated
     */
    public void setPortraitPath(String portraitPath) {
        this.portraitPath = portraitPath == null ? null : portraitPath.trim();
    }
}