package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class MonthStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_statistics.year
     *
     * @mbggenerated
     */
    private Date year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_statistics.month
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_statistics.month_income
     *
     * @mbggenerated
     */
    private Long monthIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_statistics.growth_rate
     *
     * @mbggenerated
     */
    private Double growthRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_statistics.year
     *
     * @return the value of month_statistics.year
     * @mbggenerated
     */
    public Date getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_statistics.year
     *
     * @param year the value for month_statistics.year
     * @mbggenerated
     */
    public void setYear(Date year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_statistics.month
     *
     * @return the value of month_statistics.month
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_statistics.month
     *
     * @param month the value for month_statistics.month
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_statistics.month_income
     *
     * @return the value of month_statistics.month_income
     * @mbggenerated
     */
    public Long getMonthIncome() {
        return monthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_statistics.month_income
     *
     * @param monthIncome the value for month_statistics.month_income
     * @mbggenerated
     */
    public void setMonthIncome(Long monthIncome) {
        this.monthIncome = monthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_statistics.growth_rate
     *
     * @return the value of month_statistics.growth_rate
     * @mbggenerated
     */
    public Double getGrowthRate() {
        return growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_statistics.growth_rate
     *
     * @param growthRate the value for month_statistics.growth_rate
     * @mbggenerated
     */
    public void setGrowthRate(Double growthRate) {
        this.growthRate = growthRate;
    }
}