package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.usr_id
     *
     * @mbggenerated
     */
    private Long usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.usr_address
     *
     * @mbggenerated
     */
    private String usrAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.usr_cellphone
     *
     * @mbggenerated
     */
    private String usrCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.detection_point
     *
     * @mbggenerated
     */
    private Integer detectionPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupon_id
     *
     * @mbggenerated
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_remark
     *
     * @mbggenerated
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.distance
     *
     * @mbggenerated
     */
    private Double distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_date
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.result_data
     *
     * @mbggenerated
     */
    private String resultData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.area
     *
     * @mbggenerated
     */
    private Double area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.construction_process_photo
     *
     * @mbggenerated
     */
    private String constructionProcessPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.usr_id
     *
     * @return the value of order.usr_id
     *
     * @mbggenerated
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.usr_id
     *
     * @param usrId the value for order.usr_id
     *
     * @mbggenerated
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.usr_address
     *
     * @return the value of order.usr_address
     *
     * @mbggenerated
     */
    public String getUsrAddress() {
        return usrAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.usr_address
     *
     * @param usrAddress the value for order.usr_address
     *
     * @mbggenerated
     */
    public void setUsrAddress(String usrAddress) {
        this.usrAddress = usrAddress == null ? null : usrAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.usr_cellphone
     *
     * @return the value of order.usr_cellphone
     *
     * @mbggenerated
     */
    public String getUsrCellphone() {
        return usrCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.usr_cellphone
     *
     * @param usrCellphone the value for order.usr_cellphone
     *
     * @mbggenerated
     */
    public void setUsrCellphone(String usrCellphone) {
        this.usrCellphone = usrCellphone == null ? null : usrCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.detection_point
     *
     * @return the value of order.detection_point
     *
     * @mbggenerated
     */
    public Integer getDetectionPoint() {
        return detectionPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.detection_point
     *
     * @param detectionPoint the value for order.detection_point
     *
     * @mbggenerated
     */
    public void setDetectionPoint(Integer detectionPoint) {
        this.detectionPoint = detectionPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupon_id
     *
     * @return the value of order.coupon_id
     *
     * @mbggenerated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupon_id
     *
     * @param couponId the value for order.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_remark
     *
     * @return the value of order.order_remark
     *
     * @mbggenerated
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_remark
     *
     * @param orderRemark the value for order.order_remark
     *
     * @mbggenerated
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.distance
     *
     * @return the value of order.distance
     *
     * @mbggenerated
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.distance
     *
     * @param distance the value for order.distance
     *
     * @mbggenerated
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_date
     *
     * @return the value of order.order_date
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_date
     *
     * @param orderDate the value for order.order_date
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.result_data
     *
     * @return the value of order.result_data
     *
     * @mbggenerated
     */
    public String getResultData() {
        return resultData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.result_data
     *
     * @param resultData the value for order.result_data
     *
     * @mbggenerated
     */
    public void setResultData(String resultData) {
        this.resultData = resultData == null ? null : resultData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.area
     *
     * @return the value of order.area
     *
     * @mbggenerated
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.area
     *
     * @param area the value for order.area
     *
     * @mbggenerated
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.construction_process_photo
     *
     * @return the value of order.construction_process_photo
     *
     * @mbggenerated
     */
    public String getConstructionProcessPhoto() {
        return constructionProcessPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.construction_process_photo
     *
     * @param constructionProcessPhoto the value for order.construction_process_photo
     *
     * @mbggenerated
     */
    public void setConstructionProcessPhoto(String constructionProcessPhoto) {
        this.constructionProcessPhoto = constructionProcessPhoto == null ? null : constructionProcessPhoto.trim();
    }
}