package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class PushCouponRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_coupon_record.coupon_id
     *
     * @mbggenerated
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_coupon_record.push_time
     *
     * @mbggenerated
     */
    private Date pushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_coupon_record.use_or_not
     *
     * @mbggenerated
     */
    private Boolean useOrNot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_coupon_record.coupon_id
     *
     * @return the value of push_coupon_record.coupon_id
     * @mbggenerated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_coupon_record.coupon_id
     *
     * @param couponId the value for push_coupon_record.coupon_id
     * @mbggenerated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_coupon_record.push_time
     *
     * @return the value of push_coupon_record.push_time
     * @mbggenerated
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_coupon_record.push_time
     *
     * @param pushTime the value for push_coupon_record.push_time
     * @mbggenerated
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_coupon_record.use_or_not
     *
     * @return the value of push_coupon_record.use_or_not
     * @mbggenerated
     */
    public Boolean getUseOrNot() {
        return useOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_coupon_record.use_or_not
     *
     * @param useOrNot the value for push_coupon_record.use_or_not
     * @mbggenerated
     */
    public void setUseOrNot(Boolean useOrNot) {
        this.useOrNot = useOrNot;
    }
}