package com.monster.greenfruit.pojo.domain;

public class UsrAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_advice.usr_id
     *
     * @mbggenerated
     */
    private Long usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_advice.admin_id
     *
     * @mbggenerated
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_advice.usr_advice
     *
     * @mbggenerated
     */
    private String usrAdvice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_advice.usr_id
     *
     * @return the value of usr_advice.usr_id
     * @mbggenerated
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_advice.usr_id
     *
     * @param usrId the value for usr_advice.usr_id
     * @mbggenerated
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_advice.admin_id
     *
     * @return the value of usr_advice.admin_id
     * @mbggenerated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_advice.admin_id
     *
     * @param adminId the value for usr_advice.admin_id
     * @mbggenerated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_advice.usr_advice
     *
     * @return the value of usr_advice.usr_advice
     * @mbggenerated
     */
    public String getUsrAdvice() {
        return usrAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_advice.usr_advice
     *
     * @param usrAdvice the value for usr_advice.usr_advice
     * @mbggenerated
     */
    public void setUsrAdvice(String usrAdvice) {
        this.usrAdvice = usrAdvice == null ? null : usrAdvice.trim();
    }
}