package com.monster.greenfruit.pojo.domain;

import java.util.Date;

public class YearStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_statistics.year
     *
     * @mbggenerated
     */
    private Date year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_statistics.year_income
     *
     * @mbggenerated
     */
    private Long yearIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_statistics.growth_rate
     *
     * @mbggenerated
     */
    private Double growthRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_statistics.year
     *
     * @return the value of year_statistics.year
     * @mbggenerated
     */
    public Date getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_statistics.year
     *
     * @param year the value for year_statistics.year
     * @mbggenerated
     */
    public void setYear(Date year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_statistics.year_income
     *
     * @return the value of year_statistics.year_income
     * @mbggenerated
     */
    public Long getYearIncome() {
        return yearIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_statistics.year_income
     *
     * @param yearIncome the value for year_statistics.year_income
     * @mbggenerated
     */
    public void setYearIncome(Long yearIncome) {
        this.yearIncome = yearIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_statistics.growth_rate
     *
     * @return the value of year_statistics.growth_rate
     * @mbggenerated
     */
    public Double getGrowthRate() {
        return growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_statistics.growth_rate
     *
     * @param growthRate the value for year_statistics.growth_rate
     * @mbggenerated
     */
    public void setGrowthRate(Double growthRate) {
        this.growthRate = growthRate;
    }
}